name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          yarn install
          yarn run build
      - name: Lint
        run: yarn run lint
      - name: Test Coverage
        run: npx lerna run --concurrency 1 --stream test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/coverage"

  mut:
    name: Mutation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Build
        run: |
          yarn install
          yarn run build
      - name: Run Stryker
        run: npx lerna run --concurrency 1 --stream stryker -- -- --concurrency 3
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
