name: CI

on: [push, pull_request]

jobs:
  test-win:
    name: Tests Win
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Build
        run: |
          yarn install
          yarn run build
      - name: Lint
        run: npx lerna run --concurrency 1 --stream lint:fix
      - name: Test Coverage
        run: npx lerna run --concurrency 1 --stream test

  test-macos:
    name: Tests MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Build
        run: |
          yarn install
          yarn run build
      - name: Lint
        run: npx lerna run --concurrency 1 --stream lint
      - name: Test Coverage
        run: npx lerna run --concurrency 1 --stream test

  test-ubuntu:
    name: Tests Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Build
        run: |
          yarn install
          yarn run build
      - name: Lint
        run: npx lerna run --concurrency 1 --stream lint
      - name: Test Coverage
        run: npx lerna run --concurrency 1 --stream test:cov