name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Build
        run: |
          yarn install
          yarn run build
      - name: Lint
        run: yarn run lint
      - name: Test Coverage
        run: npx lerna run --concurrency 1 --stream test:cov
